name: 'priscybot main'

on:
    push:
      branches:
        - "main"
    pull_request:
    workflow_dispatch:
permissions:
    contents: write
    id-token: write
    checks: write
    pull-requests: write
jobs:  
    set-matrix:
      name: Set Matrix
      uses: wendy-omotuebe/priscibot/.github/workflows/set-matrix.yml@main
      with:
        json_path: 'environments.json'
        env_deploy_list: '["main"]'
  
    Plan:
      needs: [set-matrix ]
      name: Terraform Plan - ${{ matrix.env }}
      strategy:
        max-parallel: 1
        matrix: ${{fromJson(needs.set-matrix.outputs.matrix)}}
      uses: wendy-omotuebe/priscibot/.github/workflows/terraform-plan.yml@main
      secrets: inherit
      with:
        tf_build_path: terraform/build/
        tf_deploy_path: terraform/deploy/
        environment: ${{ matrix.env }}
        region: ${{ matrix.region }}
        role_to_assume: ${{ matrix.role_to_assume }}
        #tf_destroy_all_resources: ${{ matrix.tf_destroy_all_resources}}
  
    Apply:
      needs: [ Plan, set-matrix ]
      name: Terraform Apply - ${{ matrix.env }}
      strategy:
        max-parallel: 1
        matrix: ${{fromJson(needs.set-matrix.outputs.matrix)}}
      uses: wendy-omotuebe/priscibot/.github/workflows/terraform-apply.yml@main
      secrets: inherit
      with:
        environment: ${{ matrix.env }}
        tf_build_path: terraform/build/
        tf_deploy_path: terraform/deploy/
        env_deploy_list: ${{ needs.set-matrix.outputs.env_deploy_list }}
        region: ${{ matrix.region }}
        role_to_assume: ${{ matrix.role_to_assume }}
        #tf_destroy_all_resources: ${{ matrix.tf_destroy_all_resources}}
        